### ISSUE TITLE
comment crud 초기 작업

### ISSUE THREAD

**Issue by leebuwon** [masil-team/Back-End#14]
# 기능 리포트
comment crud 초기 작업
## 구현 기능
comment CRUD 초기 작업
test 코드는 추후에 작업 예정

**Comment by yeongsik** [comment]
@leebuwon 무지님 
우측 에 있는 Assignees  Development , Projects 정보들 추가 했는데 해당 이슈 close 해도 되는거면 close 부탁드려요
